### ISSUE TITLE
og:url pointing to 127.0.0.1

### ISSUE THREAD

**Issue by JD557** [tiffany352/unicode-visualizer-web#43]
On the deployed version, the `og:url` is defined as `<meta property="og:url" content="https://127.0.0.1:12658/">`

Maybe a misconfiguration of `page.host` (or maybe another variable should be used there)?

https://github.com/tiffany352/unicode-visualizer-web/blob/9997b4bb4521a8570574acc1c49154974383e1d3/src/components/OpenGraph.svelte#L15-L19

**Comment by tiffany352** [comment]
Should be fixed now. Thanks for reporting it!
